### ISSUE TITLE
Repair cost inconsistencies 

### ISSUE THREAD

**Issue by SylisMC** [Pepperoni-Jabroni/RuinedEquipment#1]
Repair costs are not balanced with vanilla repair costs. For example.

- You can repair a broken sword fully from broken to max health (significantly more expensive)
OR
- Fix the item slightly, (using one item) and then repair the nearly broken item to max durability (Much cheaper)

ruined diamond sword full repair: Costs 6 diamonds & 15 levels
ruined diamond sword Alternate repair: Costs 5 diamonds & 6 levels (using 1 to slightly fix it, and 4 to fully fix it)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for the report. I'll get around to fixing this soon, but I wouldn't consider this insanely high-priority since Mojang's repair code has major discrepancies in repair costs as well for vanilla items.

**Comment by Pepperoni-Jabroni** [comment]
Fixed in revision 86fa192cc - version 1.1.1 has been published to Releases & on Curseforge.
