### ISSUE TITLE
Mending doesn't affect broken tools [1.18.1 FABRIC]

### ISSUE THREAD

**Issue by S1mpleM0use** [Pepperoni-Jabroni/RuinedEquipment#10]
Basically that's it. I do not have Better Than Mending or Clumps installed, only Ruined Equipment. Mending just ignores ruined tools

**Comment by S1mpleM0use** [comment]
Yes, I do have the corresponding option ENABLED in the config. I didn't change anything

**Comment by Pepperoni-Jabroni** [comment]
I've confirmed this in 1.5.0 as well.
