### ISSUE TITLE
Game crashes when trying to fix ruined tools with an Anvil

### ISSUE THREAD

**Issue by UlticraftMTT** [Pepperoni-Jabroni/RuinedEquipment#14]
[crash-2022-08-09_14.11.44-client.txt](https://github.com/Pepperoni-Jabroni/RuinedEquipment/files/9293961/crash-2022-08-09_14.11.44-client.txt)

When i place a ruined tool into an Anvil's repair slot, the game crashes.

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting! Were you trying to repair a "Ruined Item's Ashes"?

**Comment by calviore** [comment]
I was having the same problem so I did some experiments and found out the culprit was the config file. If you change any settings ingame (ModMenu) and don't touch the last 2 boxes it changes its null value to empty quotation marks ("") which causes the crash mentioned above.

**Comment by Pepperoni-Jabroni** [comment]
Thanks for taking a look! Will resolve this and publish a new version.

**Comment by Pepperoni-Jabroni** [comment]
Sorry this took me so long to get to, but this was fixed in v2.2.0+
