### ISSUE TITLE
Ruined gear with Mending voids any XP gained

### ISSUE THREAD

**Issue by James103** [Pepperoni-Jabroni/RuinedEquipment#3]
What if a feature made it such that if you have any ruined gear with Mending in your inventory, any XP you pick up will be voided, but every XP you pick up has a chance of turning the ruined gear back to its original form?

**Comment by Pepperoni-Jabroni** [comment]
That's a good idea! I will make this disable-able with a config, but I really like this idea. Although I'm not sure how many players have issues with their Mending items breaking haha.

**Comment by Pepperoni-Jabroni** [comment]
This has been integrated with revision e2369ea35 - submitted V1.2.0 to Curseforge. Thanks again for the suggestion!
