### ISSUE TITLE
Crash when fixing tools with an anvil on server

### ISSUE THREAD

**Issue by Taullo** [Pepperoni-Jabroni/RuinedEquipment#5]
The server crashes every time I attempt to repair a broken item in an anvil even when Fabric API is the only other mod installed. The crafting table works fine though. Not sure if there's something specific to my configuration or not, but I'm using:
- Minecraft 1.16.5
- ruined-equipment-1.2.3
- fabric-api-0.30.0+1.16
- fabric loader 0.11.1
- OpenJDK 64-Bit Server VM 15

And crash report:
[crash-2021-02-09_22.17.07-server.txt](https://github.com/Pepperoni-Jabroni/RuinedEquipment/files/5954634/crash-2021-02-09_22.17.07-server.txt)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for the thorough details, I'll try and get a fix out for this soon.

**Comment by Pepperoni-Jabroni** [comment]
This has been addressed in revision e79f2d71 & built into V1.2.4, published to Releases & Curseforge. Thanks again for the report @Taullo! Closing this out now.
